# Generated by Django 5.2.7 on 2025-10-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solanapayment',
            name='reference',
            field=models.CharField(help_text='Unique reference public key for tracking this payment on-chain (base58 encoded Solana public key)', max_length=44, unique=True),
        ),
    ]
