# Generated by Django 5.2.7 on 2025-10-27 15:21

import django.db.models.deletion
import uuid
import wallet_analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_analysis', '0002_alter_solanapayment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(help_text='The order this run belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='wallet_analysis.walletanalysisorder')),
            ],
            options={
                'verbose_name': 'Analysis Run',
                'verbose_name_plural': 'Analysis Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dune_query_id', models.IntegerField(help_text='Dune Analytics query ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if query failed', null=True)),
                ('result_csv', models.FileField(blank=True, help_text='CSV result file', null=True, upload_to=wallet_analysis.models.get_csv_upload_path)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(help_text='The analysis run this query belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='query_executions', to='wallet_analysis.analysisrun')),
            ],
            options={
                'verbose_name': 'Query Execution',
                'verbose_name_plural': 'Query Executions',
                'ordering': ['started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['order', '-created_at'], name='wallet_anal_order_i_b87de0_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['status', '-created_at'], name='wallet_anal_status_17bffa_idx'),
        ),
        migrations.AddIndex(
            model_name='queryexecution',
            index=models.Index(fields=['run', 'status'], name='wallet_anal_run_id_498dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='queryexecution',
            index=models.Index(fields=['status', '-started_at'], name='wallet_anal_status_066b1f_idx'),
        ),
    ]
