# Generated by Django 5.2.7 on 2025-10-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_analysis', '0003_analysisrun_queryexecution_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dunequeryjob',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dunequeryjob',
            name='arguments',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dunequeryjob',
            name='result_csv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dunequeryjob',
            unique_together={('order', 'query_name', 'arguments')},
        ),
    ]
