# Generated by Django 5.2.7 on 2025-10-27 18:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_analysis', '0004_alter_dunequeryjob_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='X402Query',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet', models.CharField(max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
